[2024-12-01T12:42:19.997+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-01T12:42:20.011+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: retreival_x_data.hashtag_retreive manual__2024-12-01T12:42:17.823461+00:00 [queued]>
[2024-12-01T12:42:20.019+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: retreival_x_data.hashtag_retreive manual__2024-12-01T12:42:17.823461+00:00 [queued]>
[2024-12-01T12:42:20.019+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-01T12:42:20.035+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): hashtag_retreive> on 2024-12-01 12:42:17.823461+00:00
[2024-12-01T12:42:20.043+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=967) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-01T12:42:20.045+0000] {standard_task_runner.py:72} INFO - Started process 976 to run task
[2024-12-01T12:42:20.045+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'retreival_x_data', 'hashtag_retreive', 'manual__2024-12-01T12:42:17.823461+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/retreive_data.py', '--cfg-path', '/tmp/tmpvdz44v9e']
[2024-12-01T12:42:20.046+0000] {standard_task_runner.py:105} INFO - Job 66: Subtask hashtag_retreive
[2024-12-01T12:42:20.083+0000] {task_command.py:467} INFO - Running <TaskInstance: retreival_x_data.hashtag_retreive manual__2024-12-01T12:42:17.823461+00:00 [running]> on host e824da4198b6
[2024-12-01T12:42:20.147+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nou' AIRFLOW_CTX_DAG_ID='retreival_x_data' AIRFLOW_CTX_TASK_ID='hashtag_retreive' AIRFLOW_CTX_EXECUTION_DATE='2024-12-01T12:42:17.823461+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-01T12:42:17.823461+00:00'
[2024-12-01T12:42:20.148+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-01T12:42:20.148+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-01T12:42:20.149+0000] {logging_mixin.py:190} INFO - Current task name:hashtag_retreive state:running start_date:2024-12-01 12:42:20.012606+00:00
[2024-12-01T12:42:20.149+0000] {logging_mixin.py:190} INFO - Dag name:retreival_x_data and current dag run status:running
[2024-12-01T12:42:20.149+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-01T12:42:20.151+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/retreive_data.py", line 7, in retreive_hashtag
    result = subprocess.run(
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ls /opt/airflow'
[2024-12-01T12:42:20.164+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-01T12:42:20.165+0000] {logging_mixin.py:190} INFO - Task start:2024-12-01 12:42:20.012606+00:00 end:2024-12-01 12:42:20.164528+00:00 duration:0.151922
[2024-12-01T12:42:20.165+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): hashtag_retreive> dag:<DAG: retreival_x_data> dagrun:<DagRun retreival_x_data @ 2024-12-01 12:42:17.823461+00:00: manual__2024-12-01T12:42:17.823461+00:00, state:running, queued_at: 2024-12-01 12:42:17.840636+00:00. externally triggered: True>
[2024-12-01T12:42:20.166+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: 'ls /opt/***'
[2024-12-01T12:42:20.166+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=retreival_x_data, task_id=hashtag_retreive, run_id=manual__2024-12-01T12:42:17.823461+00:00, execution_date=20241201T124217, start_date=20241201T124220, end_date=20241201T124220
[2024-12-01T12:42:20.176+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-01T12:42:20.177+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 66 for task hashtag_retreive ([Errno 2] No such file or directory: 'ls /opt/airflow'; 976)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/retreive_data.py", line 7, in retreive_hashtag
    result = subprocess.run(
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ls /opt/airflow'
[2024-12-01T12:42:20.219+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-01T12:42:20.233+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-01T12:42:20.234+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
